import type { DiseaseDatabase } from './types'
import type { Translations } from './types'

// Keyed by the trained model's actual output classes (ml/export_tfjs/labels.json),
// which come from the PlantVillage dataset - keep these in sync with that file.
export const diseaseDatabase: DiseaseDatabase = {
  'Pepper__bell___Bacterial_spot': {
    crop: 'Bell Pepper',
    severity: 'High',
    symptoms: 'Small, dark, water-soaked spots on leaves and fruit that enlarge and turn brown with a yellow halo',
    treatment: {
      chemical: 'Apply copper-based bactericides combined with mancozeb every 7-10 days',
      organic: 'Remove and destroy infected plant debris, apply copper soap sprays',
      prevention: 'Use disease-free seed, avoid overhead watering, rotate crops for 2-3 years',
    },
    confidence: 90,
  },
  'Pepper__bell___healthy': {
    crop: 'Bell Pepper',
    severity: 'None',
    symptoms: 'No visible disease symptoms detected',
    treatment: {
      chemical: 'No treatment needed',
      organic: 'Continue regular care and monitoring',
      prevention: 'Maintain good agricultural practices',
    },
    confidence: 96,
  },
  'Potato___Early_blight': {
    crop: 'Potato',
    severity: 'Medium',
    symptoms: 'Concentric rings on older leaves, yellowing around spots',
    treatment: {
      chemical: 'Apply Azoxystrobin or Chlorothalonil fungicide',
      organic: 'Remove infected leaves, apply neem oil, improve drainage',
      prevention: 'Crop rotation, avoid water stress, mulching',
    },
    confidence: 89,
  },
  'Potato___Late_blight': {
    crop: 'Potato',
    severity: 'High',
    symptoms: 'Dark, water-soaked lesions on leaves with white fungal growth on undersides in humid conditions',
    treatment: {
      chemical: 'Apply Mancozeb or Chlorothalonil fungicide every 7-10 days',
      organic: 'Remove infected foliage, apply copper-based fungicides, ensure proper air circulation',
      prevention: 'Avoid overhead irrigation, plant resistant varieties, destroy volunteer potatoes',
    },
    confidence: 94,
  },
  'Potato___healthy': {
    crop: 'Potato',
    severity: 'None',
    symptoms: 'No visible disease symptoms detected',
    treatment: {
      chemical: 'No treatment needed',
      organic: 'Continue regular care and monitoring',
      prevention: 'Maintain good agricultural practices',
    },
    confidence: 96,
  },
  'Tomato_Bacterial_spot': {
    crop: 'Tomato',
    severity: 'High',
    symptoms: 'Small, dark, greasy-looking spots on leaves, stems, and fruit',
    treatment: {
      chemical: 'Apply copper-based bactericides, avoid excessive nitrogen fertilization',
      organic: 'Remove infected plants, use copper soap sprays, improve air circulation',
      prevention: 'Use certified disease-free seed, avoid working with wet plants, rotate crops',
    },
    confidence: 88,
  },
  'Tomato_Early_blight': {
    crop: 'Tomato',
    severity: 'Medium',
    symptoms: 'Concentric "target-spot" rings on older leaves, yellowing and leaf drop',
    treatment: {
      chemical: 'Apply Chlorothalonil or Azoxystrobin fungicide',
      organic: 'Remove infected lower leaves, apply neem oil, mulch to prevent soil splash',
      prevention: 'Crop rotation, stake plants for airflow, avoid overhead watering',
    },
    confidence: 89,
  },
  'Tomato_Late_blight': {
    crop: 'Tomato',
    severity: 'High',
    symptoms: 'Dark brown spots on leaves, white fungal growth on undersides',
    treatment: {
      chemical: 'Apply Mancozeb or Chlorothalonil fungicide every 7-10 days',
      organic: 'Remove infected leaves, apply copper-based fungicides, ensure proper air circulation',
      prevention: 'Avoid overhead irrigation, plant resistant varieties, rotate crops',
    },
    confidence: 94,
  },
  'Tomato_Leaf_Mold': {
    crop: 'Tomato',
    severity: 'Medium',
    symptoms: 'Olive-green to gray fuzzy growth on underside of leaves',
    treatment: {
      chemical: 'Use chlorothalonil or copper-based fungicides',
      organic: 'Improve air circulation, remove infected leaves',
      prevention: 'Avoid overhead watering, resistant varieties',
    },
    confidence: 85,
  },
  'Tomato_Septoria_leaf_spot': {
    crop: 'Tomato',
    severity: 'Medium',
    symptoms: 'Small circular spots with dark borders and gray centers, mainly on lower leaves',
    treatment: {
      chemical: 'Apply chlorothalonil or mancozeb fungicide',
      organic: 'Remove and destroy infected leaves, mulch around base of plant',
      prevention: 'Rotate crops, avoid overhead irrigation, space plants for airflow',
    },
    confidence: 86,
  },
  'Tomato_Spider_mites_Two_spotted_spider_mite': {
    crop: 'Tomato',
    severity: 'Medium',
    symptoms: 'Fine yellow stippling on leaves, fine webbing on undersides in heavy infestations',
    treatment: {
      chemical: 'Apply miticides such as abamectin, rotate active ingredients to avoid resistance',
      organic: 'Spray insecticidal soap or neem oil, introduce predatory mites',
      prevention: 'Avoid drought stress, keep plants well watered, monitor regularly',
    },
    confidence: 82,
  },
  'Tomato__Target_Spot': {
    crop: 'Tomato',
    severity: 'Medium',
    symptoms: 'Brown lesions with concentric rings on leaves, stems, and fruit',
    treatment: {
      chemical: 'Apply chlorothalonil or azoxystrobin fungicide',
      organic: 'Remove infected debris, improve air circulation',
      prevention: 'Crop rotation, avoid leaf wetness, resistant varieties where available',
    },
    confidence: 83,
  },
  'Tomato__Tomato_YellowLeaf__Curl_Virus': {
    crop: 'Tomato',
    severity: 'High',
    symptoms: 'Upward curling and yellowing of leaves, stunted growth, spread by whiteflies',
    treatment: {
      chemical: 'Control whitefly vectors with insecticidal sprays',
      organic: 'Use reflective mulches and yellow sticky traps to reduce whiteflies',
      prevention: 'Plant resistant varieties, remove infected plants promptly, control whitefly populations',
    },
    confidence: 91,
  },
  'Tomato__Tomato_mosaic_virus': {
    crop: 'Tomato',
    severity: 'High',
    symptoms: 'Mottled light and dark green pattern on leaves, distorted leaf growth, stunted plants',
    treatment: {
      chemical: 'No chemical cure - remove and destroy infected plants',
      organic: 'Disinfect tools between plants, wash hands after handling tobacco products',
      prevention: 'Use resistant varieties, certified virus-free seed, control aphid vectors',
    },
    confidence: 90,
  },
  'Tomato_healthy': {
    crop: 'Tomato',
    severity: 'None',
    symptoms: 'No visible disease symptoms detected',
    treatment: {
      chemical: 'No treatment needed',
      organic: 'Continue regular care and monitoring',
      prevention: 'Maintain good agricultural practices',
    },
    confidence: 96,
  },
}

export const translations: Translations = {
  en: {
    title: 'AI Crop Disease Detection',
    subtitle: 'Upload or capture leaf image for instant diagnosis',
    upload: 'Upload Image',
    camera: 'Use Camera',
    analyzing: 'Analyzing...',
    disease: 'Disease Detected',
    crop: 'Crop',
    severity: 'Severity',
    confidence: 'Confidence',
    symptoms: 'Symptoms',
    treatment: 'Treatment',
    chemical: 'Chemical',
    organic: 'Organic',
    prevention: 'Prevention',
    newScan: 'New Scan',
    selectLanguage: 'Language',
  },
  hi: {
    title: 'एआई फसल रोग पहचान',
    subtitle: 'तुरंत निदान के लिए पत्ती की तस्वीर अपलोड करें',
    upload: 'फोटो अपलोड करें',
    camera: 'कैमरा उपयोग करें',
    analyzing: 'विश्लेषण हो रहा है...',
    disease: 'रोग की पहचान',
    crop: 'फसल',
    severity: 'गंभीरता',
    confidence: 'विश्वास स्तर',
    symptoms: 'लक्षण',
    treatment: 'उपचार',
    chemical: 'रासायनिक',
    organic: 'जैविक',
    prevention: 'रोकथाम',
    newScan: 'नई जांच',
    selectLanguage: 'भाषा',
  },
  ta: {
    title: 'AI பயிர் நோய் கண்டறிதல்',
    subtitle: 'உடனடி நோய்க்கண்டறிதலுக்கு இலை படத்தை பதிவேற்றவும்',
    upload: 'படத்தை பதிவேற்று',
    camera: 'கேமராவைப் பயன்படுத்து',
    analyzing: 'பகுப்பாய்வு செய்கிறது...',
    disease: 'நோய் கண்டறியப்பட்டது',
    crop: 'பயிர்',
    severity: 'தீவிரம்',
    confidence: 'நம்பிக்கை நிலை',
    symptoms: 'அறிகுறிகள்',
    treatment: 'சிகிச்சை',
    chemical: 'இரசாயன',
    organic: 'இயற்கை',
    prevention: 'தடுப்பு',
    newScan: 'புதிய ஸ்கேன்',
    selectLanguage: 'மொழி',
  },
}


